version: "3"

tasks:
  default:
    cmds:
      - task: test

  test:
    cmds:
      - cargo build --release
      - ./target/release/img2epub ./images test.epub
      - java -jar epubcheck/epubcheck.jar test.epub
      - ./target/release/get_metadata test.epub
      - rm test.epub
      - cp -r ./images ./tmp-images
      - rm ./tmp-images/metadata.json
      - |
        ./target/release/img2epub ./tmp-images test.epub \
        -t "Test Title" -c "Test Author" -p "Test Publisher" \
        --date "Test Date" -d "rtl"
      - java -jar epubcheck/epubcheck.jar test.epub
      - ./target/release/get_metadata test.epub
      - rm -rf test.epub ./tmp-images
