version: "3"

tasks:
  default:
    cmds:
      - task: test
  test:
    cmds:
      - cargo build --release
      - ./target/release/img2epub test_title ./images test.epub RTL
      - java -jar epubcheck/epubcheck.jar test.epub
      - open test.epub
