version: "3"

tasks:
  default:
    cmds:
      - task: test

  test:
    cmds:
      - cargo build --release
      - ./target/release/img2epub ./images test.epub
      - java -jar epubcheck/epubcheck.jar test.epub
      - ./target/release/get_metadata test.epub
      - rm test.epub
