name: PR Auto-merge

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
          
      - name: Install Task
        uses: arduino/setup-task@v2
          
      - name: Run tests
        run: task test

  automerge:
    runs-on: ubuntu-latest
    needs: test
    if: github.event.pull_request.user.login == 'renovate[bot]'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: ""
